### ISSUE TITLE
JavaScript/CoffeeScript not triggering Jekyll to rebuild when changed

### ISSUE THREAD

**Issue by tombell** [jekyll-assets/jekyll-assets#115] opened 2014-11-26 10:42 UTC
When editing SCSS files, Jekyll notices these changes and rebuilds. However when editing JS/CS, Jekyll doesn't rebuild.

I don't know if this is an issue with jekyll or jekyll-assets.

**Comment by jameskerr** [comment] 2015-01-23 19:38
I am also having this problem.

**Comment by peplin** [comment] 2015-02-13 02:52
Here's a "me too" - anything I can provide to help debug this?

**Comment by ixti** [comment] 2015-02-13 02:57
I think I know where this bug might come from - I just need to recheck.

**Comment by peplin** [comment] 2015-03-04 21:39
If you could describe what you think might be happening, I might be able to help debug. Thanks!

**Comment by peplin** [comment] 2015-05-08 13:57
I'm still having this issue with v1.0.0.pre.alpha1.

**Comment by envygeeks** [comment] 2015-07-23 04:47
Could this have been a Jekyll 2.4 problems? AFAIW it would be Jekyll that triggers the rebuild, unless there was a bad mtime cache (which was the cause of a lot of other problems when it came to importing assets independent of sprockets through SASS) which meant that even if there was a change detected a rebuild of the asset was never done.  We resolved this in HEAD (2.0.0) by switching to a digested cache and using Sprockets 3 file cache so we could always pull a fresh asset with find_asset and redigest against the cache.

/cc @parkr

In Jekyll3 we have no problems with jekyll-assets/HEAD (be catious in using it, it's not fully compatible with 1.0.0 yet) on the dozen or so sites I currently maintain.

**Comment by parkr** [comment] 2015-07-26 00:24
Jekyll does trigger the rebuild via [jekyll-watch](https://github.com/jekyll/jekyll-watch). It is instructed to listen to everything, excepting things in your `exclude` configuration directive. Do the CS files contain any of the items in `exclude`, such as `script` (based on above)? For example, `_assets/coffeescript/main.coffee` will be ignored because `exclude`'s are turned into a global `/regexp/`.

**Comment by envygeeks** [comment] 2015-07-26 00:31
By triggering the rebuild I mean once Jekyll rebuilds itself we are triggered through that in 1.0.0 and in 2.0.0 we hook into post and pre hooks to get triggered.

**Comment by envygeeks** [comment] 2015-10-09 18:27
This has been fixed for a while AFAIW, closing this out of this milestone, if it's not the case on 2.0.0 then please add a message on this ticket and I'll investigate the regression.

**Closed by envygeeks** 2015-10-09 18:27 UTC
