### ISSUE TITLE
Files ignored when not used in HTML

### ISSUE THREAD

**Issue by crearc** [jekyll-assets/jekyll-assets#103] opened 2014-09-26 18:47 UTC
I have some images that I include with `image-url("path/to/image.jpg")` in my SASS files for a background image. I don't use it anywhere else, but it does not compile to my `_site` folder. The `image-url` function does return the expected path with the md5 sum appended.

Any ideas? Thanks so much.

**Comment by mistermark** [comment] 2015-01-15 09:07
Same problem here. Trying to reference an image from my SASS file and it's not included with the building the project.
Something in the way of the JS files would be preferable, since that's the first thing I tried to have it included. I.e. `//= require ../assets/images/icon-trophy.svg` in your SASS file to include images like this. Or even better to have to use `{{ "logo.png" | image }}` in my SASS file. But I'll leave that choice up to you.

**Comment by ixti** [comment] 2015-02-01 19:48
Can't reproduce. Both `image-url` and `asset_path` in Sass works as expected. You can see sandbox here: https://github.com/ixti/jekyll-assets/tree/issue-103

**Comment by trkoch** [comment] 2015-02-03 09:09
Same here.

**Comment by trkoch** [comment] 2015-02-03 09:31
Sandbox works as expected. Even when moving file to sub folder and matching my _config.yml.

**Comment by ixti** [comment] 2015-02-03 09:32
I can't debug and/or help when I can't  reproduce. And "same here" reports
doesn't help in this case. A small sandbox that I can use to reproduce will
significantly speed up fixing.

**Comment by trkoch** [comment] 2015-02-03 09:41
It seems to me this is some kind of caching issue. I moved your `noise.png` in my project, changed the path, but the old image was referenced (with the wrong path, as described above). Even removing `_site` and `.sass-cache` did not work initially. Only when I touched the importing stylesheet and regenerated would I see any changes.

PS: Sorry about my initial comment.

**Comment by ixti** [comment] 2015-02-03 14:51
hm... that's interesting...

**Comment by ixti** [comment] 2015-02-03 15:07
I'm not sure I understand the workflow, though. @trkoch can you please let me know a step by step instruction how I can get that issue on [the sandbox](https://github.com/ixti/jekyll-assets/tree/issue-103)?

**Comment by brandonarbini** [comment] 2015-02-11 22:48
I know that "me too" posts aren't helpful, but...me too. I also can't seem to figure out how to trigger the condition, but a lot of my images don't end up in the compiled folder. I've tried a lot of things to get them to compile, but to no avail. If I can figure it out, I'll let you know.

**Comment by brandonarbini** [comment] 2015-02-11 23:14
I'm getting the same behavior on my laptop and my desktop. :(

**Comment by brandonarbini** [comment] 2015-02-12 00:07
Ok, well, I boiled it down to the bare minimum example at http://github.com/brandonarbini/jekyll-assets-test. I checked in the `_site` folder too. It's missing the `@2x` file. Does it do the same for anyone else?

**Comment by brandonarbini** [comment] 2015-02-12 00:39
Sorry for so many messages. The best part: if I change the order of the image tags it compiles the other image. So, it only ever compiles one image. The first one. This is super weird.

**Comment by brandonarbini** [comment] 2015-02-12 00:46
Last comment unless I figure it out, I swear. Here's a video of building the site: http://take.ms/2KWXi. Any guesses?

**Comment by ixti** [comment] 2015-02-12 04:25
Oh! Awesome! I will figure out why is that happens.

**Comment by ixti** [comment] 2015-02-12 04:27
@brandonarbini thanks for helping!

**Comment by brandonarbini** [comment] 2015-02-12 04:36
Well, I definitely found at least one reason this happens! The two images are exactly the same, so it must unique by fingerprint. I'm away from my computer right now, but I'll see if any of my missing assets have the same fingerprint later tonight. 



--
Brandon Arbini

**Comment by brandonarbini** [comment] 2015-02-12 05:18
Well, I've confirmed that in my case I had some duplicated assets with different names in other folders. So, it seems that regardless of the filename or location, if two files are identical only one will be compiled. It was a mistake to have duplicated files in the first place, but it definitely exposed an idiosyncrasy (bug?) here.

**Comment by brandonarbini** [comment] 2015-02-12 05:33
One more comment and I'm out. I couldn't reproduce the situation where the image only referenced in the stylesheet wouldn't compile. I wonder if it's related to duplicated assets too. Anyway, thanks for the gem! :)

**Comment by DynamicDyno** [comment] 2015-02-19 07:19
I'm also seeing this. When I first build or serve it generates everything in _site just fine. But then the next time I make a change, every image that's only referenced in sass is blown away from _site.

It's not happening for me on the sandbox that you created. Then again, it wasn't happening to me yesterday on my project either, but happens consistently today. I wonder if it's happening now that there are more images and more folders of images?

The same fix is working for me: adding a liquid image tag in an html file forces the generation of the images.

Sorry I can't help more. :(

**Comment by iphoting** [comment] 2015-06-21 15:57
In my case, setting `cache: false` seems to prevent this issue from happening, but I need to test further to see if this is certain.

**Closed** 2015-07-18 05:24 UTC
Labels: bug, completed-waiting-for-merge
